# Generated by Django 4.1.10 on 2023-09-23 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("details", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "town",
                    models.CharField(
                        choices=[
                            ("Southbury", "Southbury"),
                            ("Middlebury", "Middlebury"),
                        ],
                        default="Southbury",
                        max_length=30,
                    ),
                ),
            ],
            options={"db_table": "feedback",},
        ),
        migrations.CreateModel(
            name="ideas",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=24)),
                ("idea", models.TextField()),
                (
                    "idea_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "town",
                    models.CharField(
                        choices=[
                            ("Southbury", "Southbury"),
                            ("Middlebury", "Middlebury"),
                        ],
                        default="Southbury",
                        max_length=30,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("Park & Recreation", "Park & Recreation"),
                            ("School", "School"),
                            ("Library", "Library"),
                            ("Senior Center", "Senior Center"),
                            ("Shopping/Stores", "Shopping/Stores"),
                            ("Police Dept", "Police Dept"),
                            ("Fire Dept", "Fire Dept"),
                            ("Medical", "Medical"),
                            ("Tax Collector", "Tax Collector"),
                            ("Restaurants", "Restaurants"),
                            ("Environment", "Environment"),
                            ("Others", "Others"),
                        ],
                        default="Park & Recreation",
                        max_length=40,
                    ),
                ),
            ],
            options={"db_table": "ideas",},
        ),
        migrations.CreateModel(
            name="IdeaSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "town",
                    models.CharField(
                        choices=[
                            ("Southbury", "Southbury"),
                            ("Middlebury", "Middlebury"),
                        ],
                        default="Southbury",
                        max_length=30,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("Park & Recreation", "Park & Recreation"),
                            ("School", "School"),
                            ("Library", "Library"),
                            ("Senior Center", "Senior Center"),
                            ("Shopping/Stores", "Shopping/Stores"),
                            ("Police Dept", "Police Dept"),
                            ("Fire Dept", "Fire Dept"),
                            ("Medical", "Medical"),
                            ("Tax Collector", "Tax Collector"),
                            ("Restaurants", "Restaurants"),
                            ("Environment", "Environment"),
                            ("Others", "Others"),
                        ],
                        default="Park & Recreation",
                        max_length=40,
                    ),
                ),
            ],
            options={"db_table": "ideaSummary",},
        ),
        migrations.CreateModel(
            name="ProfaneIdeas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=24)),
                ("idea", models.TextField()),
                (
                    "town",
                    models.CharField(
                        choices=[
                            ("Southbury", "Southbury"),
                            ("Middlebury", "Middlebury"),
                        ],
                        default="Southbury",
                        max_length=30,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("Park & Recreation", "Park & Recreation"),
                            ("School", "School"),
                            ("Library", "Library"),
                            ("Senior Center", "Senior Center"),
                            ("Shopping/Stores", "Shopping/Stores"),
                            ("Police Dept", "Police Dept"),
                            ("Fire Dept", "Fire Dept"),
                            ("Medical", "Medical"),
                            ("Tax Collector", "Tax Collector"),
                            ("Restaurants", "Restaurants"),
                            ("Environment", "Environment"),
                            ("Others", "Others"),
                        ],
                        default="Park & Recreation",
                        max_length=40,
                    ),
                ),
            ],
            options={"db_table": "profaneIdeas",},
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disclaimer_seen", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="iSummary",
            fields=[
                (
                    "summary_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("Summary", models.TextField()),
                ("date_summarized", models.DateField(auto_now_add=True)),
                (
                    "isActive",
                    models.BooleanField(
                        choices=[(False, "No"), (True, "Yes")],
                        default=False,
                        verbose_name="isActive?",
                    ),
                ),
                (
                    "town",
                    models.CharField(
                        choices=[
                            ("Southbury", "Southbury"),
                            ("Middlebury", "Middlebury"),
                        ],
                        default="Southbury",
                        max_length=30,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("Park & Recreation", "Park & Recreation"),
                            ("School", "School"),
                            ("Library", "Library"),
                            ("Senior Center", "Senior Center"),
                            ("Shopping/Stores", "Shopping/Stores"),
                            ("Police Dept", "Police Dept"),
                            ("Fire Dept", "Fire Dept"),
                            ("Medical", "Medical"),
                            ("Tax Collector", "Tax Collector"),
                            ("Restaurants", "Restaurants"),
                            ("Environment", "Environment"),
                            ("Others", "Others"),
                        ],
                        default="Park & Recreation",
                        max_length=40,
                    ),
                ),
                (
                    "ideas",
                    models.ManyToManyField(
                        related_name="i_summaries",
                        through="app_master.IdeaSummary",
                        to="app_master.ideas",
                    ),
                ),
            ],
            options={"db_table": "iSummary",},
        ),
        migrations.AddField(
            model_name="ideasummary",
            name="Summary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_master.isummary"
            ),
        ),
        migrations.AddField(
            model_name="ideasummary",
            name="idea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_master.ideas"
            ),
        ),
    ]
